from typing import Any
"""
board
"""
    board.A0: Any = ...
    A1: Any = ...
    A2: Any = ...
    MICOUT: Any = ...
    MICIN: Any = ...
    SDA: Any = ...
    SCL: Any = ...
    ACCELEROMETER_SDA: Any = ...
    ACCELEROMETER_SCL: Any = ...
    COL0: Any = ...
    COL1: Any = ...
    COL2: Any = ...
    COL3: Any = ...
    COL4: Any = ...
    COL5: Any = ...
    COL6: Any = ...
    COL7: Any = ...
    ROW0: Any = ...
    ROW1: Any = ...
    ROW2: Any = ...
    ROW3: Any = ...
    INT: Any = ...
    NEOPIXEL: Any = ...
    APA102_MOSI: Any = ...
    APA102_SCK: Any = ...
    I2C: Any = ...
