from typing import Any
"""
board
"""
    board.AREF: Any = ...
    A0: Any = ...
    A1: Any = ...
    A2: Any = ...
    A3: Any = ...
    A4: Any = ...
    A5: Any = ...
    A6: Any = ...
    SCK: Any = ...
    MOSI: Any = ...
    MISO: Any = ...
    D0: Any = ...
    RX: Any = ...
    D1: Any = ...
    TX: Any = ...
    SDA: Any = ...
    SCL: Any = ...
    D5: Any = ...
    D6: Any = ...
    D9: Any = ...
    D10: Any = ...
    D11: Any = ...
    D12: Any = ...
    D13: Any = ...
    I2C: Any = ...
    SPI: Any = ...
    UART: Any = ...
