from typing import Any
"""
board
"""
    board.D2: Any = ...
    D6: Any = ...
    D7: Any = ...
    D10: Any = ...
    D11: Any = ...
    LED: Any = ...
    D27: Any = ...
    D28: Any = ...
    SDA: Any = ...
    SCL: Any = ...
    SCK: Any = ...
    MOSI: Any = ...
    MISO: Any = ...
    D18: Any = ...
    SPI: Any = ...
