from typing import Any
"""
board
"""
    board.D0: Any = ...
    A2: Any = ...
    SDA: Any = ...
    D1: Any = ...
    A0: Any = ...
    D2: Any = ...
    A1: Any = ...
    SCL: Any = ...
    MISO: Any = ...
    D4: Any = ...
    A4: Any = ...
    TX: Any = ...
    MOSI: Any = ...
    D3: Any = ...
    A3: Any = ...
    RX: Any = ...
    SCK: Any = ...
    D13: Any = ...
    APA102_MOSI: Any = ...
    APA102_SCK: Any = ...
    I2C: Any = ...
    SPI: Any = ...
    UART: Any = ...
