from typing import Any
"""
board
"""
    board.A1: Any = ...
    RX: Any = ...
    A2: Any = ...
    TX: Any = ...
    A3: Any = ...
    A4: Any = ...
    A5: Any = ...
    SCL: Any = ...
    A6: Any = ...
    SDA: Any = ...
    A7: Any = ...
    A8: Any = ...
    POWER1: Any = ...
    DIR1: Any = ...
    POWER2: Any = ...
    DIR2: Any = ...
    POWER3: Any = ...
    DIR3: Any = ...
    POWER4: Any = ...
    DIR4: Any = ...
    NEOPIXEL: Any = ...
    I2C: Any = ...
    UART: Any = ...
