from typing import Any
"""
board
"""
    board.MICROPHONE_CLOCK: Any = ...
    MICROPHONE_DATA: Any = ...
    RIGHT_TFT_CS: Any = ...
    RIGHT_TFT_DC: Any = ...
    LEFT_TFT_CS: Any = ...
    LEFT_TFT_DC: Any = ...
    I2C: Any = ...
    DISPLAY: Any = ...
    RIGHT_DISPLAY: Any = ...
