from typing import Any
"""
board
"""
    board.SPEAKER: Any = ...
    HEADPHONE_LEFT: Any = ...
    A0: Any = ...
    HEADPHONE_RIGHT: Any = ...
    A1: Any = ...
    D2: Any = ...
    A2: Any = ...
    NOSE: Any = ...
    D3: Any = ...
    A3: Any = ...
    D13: Any = ...
    SDA: Any = ...
    SCL: Any = ...
    ACCELEROMETER_INTERRUPT: Any = ...
    SPEAKER_ENABLE: Any = ...
    MICROPHONE_CLOCK: Any = ...
    MICROPHONE_DATA: Any = ...
    RIGHT_TFT_LITE: Any = ...
    RIGHT_TFT_MOSI: Any = ...
    RIGHT_TFT_SCK: Any = ...
    RIGHT_TFT_RST: Any = ...
    RIGHT_TFT_CS: Any = ...
    RIGHT_TFT_DC: Any = ...
    LEFT_TFT_MOSI: Any = ...
    LEFT_TFT_SCK: Any = ...
    LEFT_TFT_CS: Any = ...
    LEFT_TFT_DC: Any = ...
    I2C: Any = ...
    DISPLAY: Any = ...
    RIGHT_DISPLAY: Any = ...
