from typing import Any
"""
board
"""
    board.A0: Any = ...
    A1: Any = ...
    A4: Any = ...
    A5: Any = ...
    A6: Any = ...
    A7: Any = ...
    B1: Any = ...
    B10: Any = ...
    B13: Any = ...
    B14: Any = ...
    B15: Any = ...
    B0: Any = ...
    B9: Any = ...
    B8: Any = ...
    B7: Any = ...
    B6: Any = ...
    B5: Any = ...
    B4: Any = ...
    B3: Any = ...
    A10: Any = ...
    A8: Any = ...
    LED1: Any = ...
    LED2: Any = ...
    BTN: Any = ...
    ESP_RX: Any = ...
    ESP_TX: Any = ...
    ESP_GPIO0: Any = ...
    ESP_CHPD: Any = ...
    ESP_GPIO13: Any = ...
