from typing import Any
"""
board
"""
    board.SCK: Any = ...
    MOSI: Any = ...
    MISO: Any = ...
    SCL: Any = ...
    SDA: Any = ...
    UART: Any = ...
    SPI: Any = ...
    I2C: Any = ...
    BACKLIGHT: Any = ...
    DISP_PWR: Any = ...
    TFT_CS: Any = ...
    TFT_DC: Any = ...
    TFT_RESET: Any = ...
    CTP_RESET: Any = ...
    CTP_INT: Any = ...
    CHRG_STAT: Any = ...
    BAT_VDIV: Any = ...
    VBUS_PRESENT: Any = ...
    RTC_RESET: Any = ...
    RTC_INT: Any = ...
    ACCEL_INT1: Any = ...
    ACCEL_INT2: Any = ...
    HAPTIC_INT: Any = ...
    HAPTIC_ENABLE: Any = ...
    SMC_RESET: Any = ...
    BUTTON0: Any = ...
    BUTTON1: Any = ...
