from typing import Any
"""
board
"""
    board.AUDIO_INT: Any = ...
    AUDIO_SYNC: Any = ...
    AUDIO_BCLK: Any = ...
    AUDIO_RXD: Any = ...
    AUDIO_TXD: Any = ...
    AUDIO_MCLK: Any = ...
    SPDIF_IN: Any = ...
    SPDIF_OUT: Any = ...
    FREELINK_TX: Any = ...
    FREELINK_RX: Any = ...
    I2C: Any = ...
    SPI: Any = ...
    UART: Any = ...
