from typing import Any
"""
board
"""
    board.PIEZO: Any = ...
    VOLTAGE_MONITOR: Any = ...
    SENSOR_IN: Any = ...
    MOTOR_OUT_1: Any = ...
    MOTOR_OUT_2: Any = ...
    LED_STATUS: Any = ...
    SCL: Any = ...
    SDA: Any = ...
    DOTSTAR_DI: Any = ...
    DOTSTAR_CI: Any = ...
    I2C: Any = ...
