from typing import Any
"""
board
"""
    board.SCK: Any = ...
    MOSI: Any = ...
    MISO: Any = ...
    DAC_CS: Any = ...
    G1: Any = ...
    G2: Any = ...
    G3: Any = ...
    G4: Any = ...
    NEOPIXEL: Any = ...
    SPI: Any = ...
