from typing import Any
"""
board
"""
    board.D0: Any = ...
    D1: Any = ...
    D2: Any = ...
    D3: Any = ...
    D4: Any = ...
    D5: Any = ...
    A0: Any = ...
    A1: Any = ...
    A2: Any = ...
    A3: Any = ...
    A4: Any = ...
    A5: Any = ...
    LED_G: Any = ...
    LED_R: Any = ...
    LED_B: Any = ...
    MOSI: Any = ...
    MISO: Any = ...
    SCK: Any = ...
    SCL: Any = ...
    SDA: Any = ...
    RX: Any = ...
    TX: Any = ...
    RX2: Any = ...
    TX2: Any = ...
    I2C: Any = ...
    SPI: Any = ...
    UART: Any = ...
