from typing import Any
"""
board
"""
    board.BUTTON_LEFT: Any = ...
    BUTTON_RIGHT: Any = ...
    BUTTON_UP: Any = ...
    BUTTON_DOWN: Any = ...
    BUTTON_O: Any = ...
    BUTTON_X: Any = ...
    BUTTON_Z: Any = ...
    P1: Any = ...
    P2: Any = ...
    P3: Any = ...
    P4: Any = ...
    P5: Any = ...
    P6: Any = ...
    P7: Any = ...
    TFT_RST: Any = ...
    TFT_DC: Any = ...
    TFT_MOSI: Any = ...
    TFT_SCK: Any = ...
    TFT_CS: Any = ...
    SPEAKER: Any = ...
    SDA: Any = ...
    SCL: Any = ...
    SCK: Any = ...
    MOSI: Any = ...
    MISO: Any = ...
    TX: Any = ...
    RX: Any = ...
    I2C: Any = ...
    SPI: Any = ...
    UART: Any = ...
    DISPLAY: Any = ...
