from typing import Any
"""
board
"""
    board.D1: Any = ...
    D2: Any = ...
    D3: Any = ...
    D4: Any = ...
    D5: Any = ...
    D6: Any = ...
    D7: Any = ...
    D8: Any = ...
    D9: Any = ...
    D10: Any = ...
    D11: Any = ...
    D12: Any = ...
    D13: Any = ...
    D14: Any = ...
    D15: Any = ...
    D16: Any = ...
    D17: Any = ...
    D18: Any = ...
    MOSI: Any = ...
    MISO: Any = ...
    SCK: Any = ...
    TX: Any = ...
    RX: Any = ...
    SCL: Any = ...
    SDA: Any = ...
    L: Any = ...
    I2C: Any = ...
    SPI: Any = ...
    UART: Any = ...
