from typing import Any
"""
board
"""
    board.A5: Any = ...
    A6: Any = ...
    NFC1: Any = ...
    NFC2: Any = ...
    D5: Any = ...
    D6: Any = ...
    D7: Any = ...
    D8: Any = ...
    D13: Any = ...
    D14: Any = ...
    D15: Any = ...
    SCK: Any = ...
    MOSI: Any = ...
    MISO: Any = ...
    CS: Any = ...
    BUSY: Any = ...
    DC: Any = ...
    RES: Any = ...
    EINK_EN: Any = ...
    TX: Any = ...
    RX: Any = ...
    SCL: Any = ...
    SDA: Any = ...
    L: Any = ...
    RED_LED: Any = ...
    BLUE_LED: Any = ...
    GREEN_LED: Any = ...
    UART: Any = ...
    SPI: Any = ...
    I2C: Any = ...
