from typing import Any
"""
board
"""
    board.D0: Any = ...
    D1: Any = ...
    RFM9X_D0: Any = ...
    RFM9X_D1: Any = ...
    RFM9X_D2: Any = ...
    RFM9X_D5: Any = ...
    RFM9X_RST: Any = ...
    RFM9X_CS: Any = ...
    SCK: Any = ...
    MOSI: Any = ...
    MISO: Any = ...
    SPI: Any = ...
