import microcontroller
from typing import Any

"""
analogio
"""


# shared-bindings/analogio/AnalogIn.c:53
class AnalogIn:
    def __init__(self, pin: microcontroller.Pin): ...
    def deinit(self, ) -> Any: ...
    def __enter__(self, ) -> Any: ...
    def __exit__(self, ) -> Any: ...
    value: Any = ...
    reference_voltage: Any = ...

# shared-bindings/analogio/AnalogOut.c:55
class AnalogOut:
    def __init__(self, pin: microcontroller.Pin): ...
    def deinit(self, ) -> Any: ...
    def __enter__(self, ) -> Any: ...
    def __exit__(self, ) -> Any: ...
    value: Any = ...
