import typing
from typing import Any

"""
audiomp3
"""


# shared-bindings/audiomp3/MP3Decoder.c:44
class MP3:
    def __init__(self, file: typing.BinaryIO, buffer: bytearray): ...
    def deinit(self, ) -> Any: ...
    def __enter__(self, ) -> Any: ...
    def __exit__(self, ) -> Any: ...
    file: Any = ...
    sample_rate: Any = ...
    bits_per_sample: Any = ...
    channel_count: Any = ...
    rms_level: Any = ...
