import array
import typing
from typing import Any

"""
audiocore
"""


# shared-bindings/audiocore/RawSample.c:45
class RawSample:
    def __init__(self, buffer: array.array, *, channel_count: int = 1, sample_rate: int = 8000): ...
    def deinit(self, ) -> Any: ...
    def __enter__(self, ) -> Any: ...
    def __exit__(self, ) -> Any: ...
    sample_rate: Any = ...

# shared-bindings/audiocore/WaveFile.c:45
class WaveFile:
    def __init__(self, file: typing.BinaryIO, buffer: bytearray): ...
    def deinit(self, ) -> Any: ...
    def __enter__(self, ) -> Any: ...
    def __exit__(self, ) -> Any: ...
    sample_rate: Any = ...
    bits_per_sample: Any = ...
    channel_count: Any = ...
