import microcontroller
from typing import Any

"""
audiobusio
"""


# shared-bindings/audiobusio/I2SOut.c:45
class I2SOut:
    def __init__(self, bit_clock: microcontroller.Pin, word_select: microcontroller.Pin, data: microcontroller.Pin, *, left_justified: bool): ...
    def deinit(self, ) -> Any: ...
    def __enter__(self, ) -> Any: ...
    def __exit__(self, ) -> Any: ...
    def play(self, sample: Any, *, loop: Any = False) -> Any: ...
    def stop(self, ) -> Any: ...
    playing: Any = ...
    def pause(self, ) -> Any: ...
    def resume(self, ) -> Any: ...
    paused: Any = ...

# shared-bindings/audiobusio/PDMIn.c:46
class PDMIn:
    def __init__(self, clock_pin: microcontroller.Pin, data_pin: microcontroller.Pin, *, sample_rate: int = 16000, bit_depth: int = 8, mono: bool = True, oversample: int = 64, startup_delay: float = 0.11): ...
    def deinit(self, ) -> Any: ...
    def __enter__(self, ) -> Any: ...
    def __exit__(self, ) -> Any: ...
    def record(self, destination: Any, destination_length: Any) -> Any: ...
    sample_rate: Any = ...
