from typing import Any

"""
audiomixer
"""


# shared-bindings/audiomixer/Mixer.c:48
class Mixer:
    def __init__(self, voice_count: int = 2, buffer_size: int = 1024, channel_count: int = 2, bits_per_sample: int = 16, samples_signed: bool = True, sample_rate: int = 8000): ...
    def deinit(self, ) -> Any: ...
    def __enter__(self, ) -> Any: ...
    def __exit__(self, ) -> Any: ...
    playing: Any = ...
    sample_rate: Any = ...
    voice: Any = ...
    def play(self, sample: Any, *, voice: Any = 0, loop: Any = False) -> Any: ...
    def stop_voice(self, voice: Any = 0) -> Any: ...

# shared-bindings/audiomixer/MixerVoice.c:47
class MixerVoice:
    def __init__(self, ): ...
    def play(self, sample: Any, *, loop: Any = False) -> Any: ...
    def stop(self, ) -> Any: ...
    level(): Any = ...
    playing: Any = ...
