import Group
from typing import Any

"""
framebufferio
"""


# shared-bindings/framebufferio/FramebufferDisplay.c:52
class FramebufferDisplay:
    def __init__(self, framebuffer: Any, *, rotation: int = 0, auto_refresh: bool = True): ...
    def show(self, group: Group) -> Any: ...
    def refresh(self, *, target_frames_per_second: int = 60, minimum_frames_per_second: int = 1) -> Any: ...
    auto_refresh: Any = ...
    brightness: Any = ...
    auto_brightness: Any = ...
    width: Any = ...
    height: Any = ...
    rotation: Any = ...
    framebuffer: Any = ...
    def fill_row(self, y: int, buffer: bytearray) -> Any: ...
