import microcontroller
from typing import Any

"""
frequencyio
"""


# shared-bindings/frequencyio/FrequencyIn.c:51
class FrequencyIn:
    def __init__(self, pin: microcontroller.Pin, capture_period: int = 10): ...
    def deinit(self, ) -> Any: ...
    def __enter__(self, ) -> Any: ...
    def __exit__(self, ) -> Any: ...
    def pause(self, ) -> Any: ...
    def resume(self, ) -> Any: ...
    def clear(self, ) -> Any: ...
    capture_period: Any = ...
    def __get__(self, index: Any) -> Any: ...
