import i2cslave
import microcontroller
from typing import Any

"""
i2cslave
"""


# shared-bindings/i2cslave/I2CSlave.c:57
class I2CSlave:
    def __init__(self, scl: microcontroller.Pin, sda: microcontroller.Pin, addresses: tuple, smbus: bool = False): ...
    def deinit(self, ) -> Any: ...
    def __enter__(self, ) -> Any: ...
    def __exit__(self, ) -> Any: ...
    def request(self, timeout: float = -1) -> Any: ...

# shared-bindings/i2cslave/I2CSlave.c:235
class I2CSlaveRequest:
    def __init__(self, slave: i2cslave.I2CSlave, address: int, is_read: bool, is_restart: bool): ...
    def __enter__(self, ) -> Any: ...
    def __exit__(self, ) -> Any: ...
    address: Any = ...
    is_read: Any = ...
    is_restart: Any = ...
    def read(self, n: int = -1, ack: bool = True) -> Any: ...
    def write(self, buffer: bytearray) -> Any: ...
    def ack(self, ack: bool = True) -> Any: ...
