from typing import Any

"""
math
"""

    e: Any = ...
    pi: Any = ...

# shared-bindings/math/__init__.c:101
def acos(x: Any) -> Any: ...

# shared-bindings/math/__init__.c:105
def asin(x: Any) -> Any: ...

# shared-bindings/math/__init__.c:109
def atan(x: Any) -> Any: ...

# shared-bindings/math/__init__.c:113
def atan2(y: Any, x: Any) -> Any: ...

# shared-bindings/math/__init__.c:117
def ceil(x: Any) -> Any: ...

# shared-bindings/math/__init__.c:121
def copysign(x: Any, y: Any) -> Any: ...

# shared-bindings/math/__init__.c:125
def cos(x: Any) -> Any: ...

# shared-bindings/math/__init__.c:129
def degrees(x: Any) -> Any: ...

# shared-bindings/math/__init__.c:133
def exp(x: Any) -> Any: ...

# shared-bindings/math/__init__.c:137
def fabs(x: Any) -> Any: ...

# shared-bindings/math/__init__.c:141
def floor(x: Any) -> Any: ...

# shared-bindings/math/__init__.c:145
def fmod(x: Any, y: Any) -> Any: ...

# shared-bindings/math/__init__.c:149
def frexp(x: Any) -> Any: ...

# shared-bindings/math/__init__.c:156
def isfinite(x: Any) -> Any: ...

# shared-bindings/math/__init__.c:160
def isinf(x: Any) -> Any: ...

# shared-bindings/math/__init__.c:164
def isnan(x: Any) -> Any: ...

# shared-bindings/math/__init__.c:168
def ldexp(x: Any, exp: Any) -> Any: ...

# shared-bindings/math/__init__.c:172
def modf(x: Any) -> Any: ...

# shared-bindings/math/__init__.c:177
def pow(x: Any, y: Any) -> Any: ...

# shared-bindings/math/__init__.c:181
def radians(x: Any) -> Any: ...

# shared-bindings/math/__init__.c:185
def sin(x: Any) -> Any: ...

# shared-bindings/math/__init__.c:189
def sqrt(x: Any) -> Any: ...

# shared-bindings/math/__init__.c:193
def tan(x: Any) -> Any: ...

# shared-bindings/math/__init__.c:197
def trunc(x: Any) -> Any: ...
