from typing import Any

"""
pixelbuf
"""


# shared-bindings/_pixelbuf/PixelBuf.c:54
class PixelBuf:
    def __init__(self, size: int, *, byteorder: str = "BGR", brightness: float = 0, auto_write: bool = False, header: bytes = b"", trailer: bytes = b""): ...
    bpp: Any = ...
    brightness: Any = ...
    auto_write: Any = ...
    byteorder: Any = ...
    def show(self, ) -> Any: ...

# shared-bindings/_pixelbuf/PixelBuf.c:268
def fill(color: Any) -> Any: ...
    def __getitem__(self, index: Any) -> Any: ...
    def __setitem__(self, index: Any, value: Any) -> Any: ...
