import microcontroller

"""
ps2io
"""


# shared-bindings/ps2io/Ps2.c:50
class Ps2:
    def __init__(self, data_pin: microcontroller.Pin, clock_pin: microcontroller.Pin): ...
    def deinit(self, ) -> Any: ...
    def __enter__(self, ) -> Any: ...
    def __exit__(self, ) -> Any: ...
    def popleft(self, ) -> Any: ...
    def sendcmd(self, byte: int) -> Any: ...
    def clear_errors(self, ) -> Any: ...
    def __len__(self, ) -> Any: ...
