from typing import Any

"""
rgbmatrix
"""


# shared-bindings/rgbmatrix/RGBMatrix.c:138
class RGBMatrix:
    def __init__(self, *, width: Any, bit_depth: Any, rgb_pins: Any, addr_pins: Any, clock_pin: Any, latch_pin: Any, output_enable_pin: Any, doublebuffer: Any = True, framebuffer: Any = None, height: Any = 0): ...
    def deinit(self, ) -> Any: ...
    brightness: Any = ...
    def refresh(self, ) -> Any: ...
    width: Any = ...
    height: Any = ...
