import microcontroller
from typing import Any

"""
rotaryio
"""


# shared-bindings/rotaryio/IncrementalEncoder.c:44
class IncrementalEncoder:
    def __init__(self, pin_a: microcontroller.Pin, pin_b: microcontroller.Pin): ...
    def deinit(self, ) -> Any: ...
    def __enter__(self, ) -> Any: ...
    def __exit__(self, ) -> Any: ...
    position: Any = ...
