from typing import Any

"""
socket
"""


# shared-bindings/socket/__init__.c:54
class socket:
    def __init__(self, family: int, type: int, proto: int): ...
    def bind(self, address: tuple) -> Any: ...
    def listen(self, backlog: int) -> Any: ...
    def accept(self, ) -> Any: ...
    def connect(self, address: tuple) -> Any: ...
    def send(self, bytes: bytes) -> Any: ...
    def recv_into(self, buffer: bytearray, bufsize: int) -> Any: ...
    def recv(self, bufsize: int) -> Any: ...
    def sendto(self, bytes: bytes, address: tuple) -> Any: ...
    def recvfrom(self, bufsize: int) -> Any: ...
    def setsockopt(self, level: Any, optname: Any, value: Any) -> Any: ...
    def settimeout(self, value: int) -> Any: ...
    def setblocking(self, flag: bool) -> Any: ...

# shared-bindings/socket/__init__.c:516
def getaddrinfo(host: Any, port: Any) -> Any: ...
