from typing import Any

"""
storage
"""


# shared-bindings/storage/__init__.c:51
def mount(filesystem: Any, mount_path: Any, *, readonly: bool = False) -> Any: ...

# shared-bindings/storage/__init__.c:88
def umount(mount: Any) -> Any: ...

# shared-bindings/storage/__init__.c:106
def remount(mount_path: Any, readonly: bool = False, *, disable_concurrent_write_protection: bool = False) -> Any: ...

# shared-bindings/storage/__init__.c:136
def getmount(mount_path: Any) -> Any: ...

# shared-bindings/storage/__init__.c:145
def erase_filesystem() -> Any: ...

# shared-bindings/storage/__init__.c:174
class VfsFat:
    def __init__(self, block_device: Any): ...
    label: Any = ...
    def mkfs(self, ) -> Any: ...
    def open(self, path: Any, mode: Any) -> Any: ...
    def ilistdir(self, path: Any) -> Any: ...
    def mkdir(self, path: Any) -> Any: ...
    def rmdir(self, path: Any) -> Any: ...
    def stat(self, path: Any) -> Any: ...
    def statvfs(self, path: Any) -> Any: ...
    def mount(self, readonly: Any, mkfs: Any) -> Any: ...
    def umount(self, ) -> Any: ...
