from typing import Any

"""
supervisor
"""


# shared-bindings/supervisor/Runtime.c:46
class Runtime:
    def __init__(self, ): ...
    runtime.serial_connected: Any = ...
    runtime.serial_bytes_available: Any = ...
    runtime: Any = ...
    def enable_autoreload(self, ) -> Any: ...
    def disable_autoreload(self, ) -> Any: ...
    def set_rgb_status_brightness(self, ) -> Any: ...
    def reload(self, ) -> Any: ...
    def set_next_stack_limit(self, size: Any) -> Any: ...
