import microcontroller
from typing import Any

"""
touchio
"""


# shared-bindings/touchio/TouchIn.c:57
class TouchIn:
    def __init__(self, pin: microcontroller.Pin): ...
    def deinit(self, ) -> Any: ...
    def __enter__(self, ) -> Any: ...
    def __exit__(self, ) -> Any: ...
    value: Any = ...
    raw_value: Any = ...
    threshold: Any = ...
