from typing import Any

"""
usb_hid
"""

    usb_hid.devices: Any = ...

# shared-bindings/usb_hid/Device.c:44
class Device:
    def __init__(self, ): ...
    def send_report(self, buf: Any) -> Any: ...
    usage_page: Any = ...
    usage: Any = ...
