from typing import Any
"""
board
"""
    board.P0: Any = ...
    P1: Any = ...
    P2: Any = ...
    P3: Any = ...
    P4: Any = ...
    P5: Any = ...
    P6: Any = ...
    P7: Any = ...
    P8: Any = ...
    P9: Any = ...
    LED1: Any = ...
    LED2: Any = ...
    LED3: Any = ...
    LED4: Any = ...
    LED_RED: Any = ...
    LED_GREEN: Any = ...
    LED_BLUE: Any = ...
    LED_IR: Any = ...
    UART1_TX: Any = ...
    UART1_RX: Any = ...
    UART3_TX: Any = ...
    UART3_RX: Any = ...
    I2C2_SCL: Any = ...
    I2C2_SDA: Any = ...
    I2C4_SCL: Any = ...
    I2C4_SDA: Any = ...
    SPI2_NSS: Any = ...
    SPI2_SCK: Any = ...
    SPI2_MISO: Any = ...
    SPI2_MOSI: Any = ...
