from typing import Any
"""
board
"""
    board.B15: Any = ...
    B14: Any = ...
    B13: Any = ...
    B10: Any = ...
    B1: Any = ...
    A7: Any = ...
    A6: Any = ...
    A5: Any = ...
    B3: Any = ...
    B4: Any = ...
    B5: Any = ...
    B6: Any = ...
    B7: Any = ...
    A8: Any = ...
    A4: Any = ...
    A3: Any = ...
    A2: Any = ...
    A1: Any = ...
    A0: Any = ...
    A10: Any = ...
    B9: Any = ...
    B8: Any = ...
    BTN: Any = ...
    LED1: Any = ...
    LED2: Any = ...
