from typing import Any
"""
board
"""
    board.SPI_CSN: Any = ...
    SPI_MISO: Any = ...
    SPI_MOSI: Any = ...
    SPI_SCK: Any = ...
    NFC1: Any = ...
    NFC2: Any = ...
    I2S_LRCK: Any = ...
    I2S_SDIN: Any = ...
    I2S_SCK: Any = ...
    LED: Any = ...
    CHG: Any = ...
    PWM: Any = ...
    PWM_N: Any = ...
    UART: Any = ...
    SPI: Any = ...
    I2C: Any = ...
