from typing import Any
"""
board
"""
    board.RX: Any = ...
    TX: Any = ...
    RED: Any = ...
    GREEN: Any = ...
    BLUE: Any = ...
    SDA: Any = ...
    SCL: Any = ...
    I2C: Any = ...
    SPI: Any = ...
    UART: Any = ...
