from typing import Any
"""
board
"""
    board.B12: Any = ...
    B13: Any = ...
    B14: Any = ...
    B15: Any = ...
    A8: Any = ...
    A9: Any = ...
    A10: Any = ...
    A11: Any = ...
    A12: Any = ...
    A15: Any = ...
    B3: Any = ...
    B4: Any = ...
    B5: Any = ...
    B6: Any = ...
    B7: Any = ...
    B8: Any = ...
    B9: Any = ...
    B10: Any = ...
    B2: Any = ...
    B1: Any = ...
    B0: Any = ...
    A7: Any = ...
    A6: Any = ...
    A5: Any = ...
    A4: Any = ...
    A3: Any = ...
    A2: Any = ...
    A1: Any = ...
    A0: Any = ...
    C15: Any = ...
    C14: Any = ...
    C13: Any = ...
    LED: Any = ...
