from typing import Any
"""
board
"""
    board.A3: Any = ...
    A4: Any = ...
    SCK: Any = ...
    MOSI: Any = ...
    D6: Any = ...
    D8: Any = ...
    D9: Any = ...
    D10: Any = ...
    D13: Any = ...
    UART: Any = ...
