from typing import Any
"""
board
"""
    board.SCK: Any = ...
    MOSI: Any = ...
    MISO: Any = ...
    radioCS: Any = ...
    WAKE: Any = ...
    SHDWN: Any = ...
    PWDWN: Any = ...
    TST: Any = ...
    FSYNC: Any = ...
    VCLK: Any = ...
    FSYNC: Any = ...
    MD: Any = ...
    MC: Any = ...
    PA08: Any = ...
    PA10: Any = ...
    PA09: Any = ...
    PA06: Any = ...
    DAC0: Any = ...
    TX: Any = ...
    RX: Any = ...
    SDA: Any = ...
    SCL: Any = ...
    LED: Any = ...
    UART: Any = ...
    I2C: Any = ...
    SPI: Any = ...
