from typing import Any
"""
board
"""
    board.A0: Any = ...
    A1: Any = ...
    A2: Any = ...
    A3: Any = ...
    D0: Any = ...
    D1: Any = ...
    D2: Any = ...
    D3: Any = ...
    D4: Any = ...
    D5: Any = ...
    D6: Any = ...
    D7: Any = ...
    D8: Any = ...
    D9: Any = ...
    D10: Any = ...
    D11: Any = ...
    D12: Any = ...
    D13: Any = ...
    TX: Any = ...
    RX: Any = ...
    MOSI: Any = ...
    SCK: Any = ...
    MISO: Any = ...
    SCL: Any = ...
    SDA: Any = ...
    LED: Any = ...
    BLUE_LED: Any = ...
    GREEN_LED: Any = ...
    YELLOW_LED: Any = ...
    I2C: Any = ...
    SPI: Any = ...
    UART: Any = ...
