from typing import Any
"""
board
"""
    board.MICROPHONE_CLOCK: Any = ...
    MICROPHONE_DATA: Any = ...
    TFT_RESET: Any = ...
    TFT_BACKLIGHT: Any = ...
    TFT_CS: Any = ...
    TFT_DC: Any = ...
    TFT_SCK: Any = ...
    TFT_MOSI: Any = ...
    SCL: Any = ...
    SDA: Any = ...
    I2C: Any = ...
    SPI: Any = ...
    DISPLAY: Any = ...
    BUTTON_SW1: Any = ...
    BUTTON_SW2: Any = ...
    BUTTON_SW3: Any = ...
    BUTTON_SW4: Any = ...
