from typing import Any
"""
board
"""
    board.ANMB: Any = ...
    ANVLIM: Any = ...
    AN5V: Any = ...
    MBPWM: Any = ...
    MBINT: Any = ...
    MBCS: Any = ...
    MBRST: Any = ...
    LED1: Any = ...
    LED2: Any = ...
    LED3: Any = ...
    RX: Any = ...
    TX: Any = ...
    USBHOSTEN: Any = ...
    USBRESET: Any = ...
    USBBCEN: Any = ...
    SDA: Any = ...
    SCL: Any = ...
    SDA2: Any = ...
    SCL2: Any = ...
    SCK: Any = ...
    MOSI: Any = ...
    MISO: Any = ...
    I2C: Any = ...
    SPI: Any = ...
    UART: Any = ...
