from typing import Any
"""
board
"""
    board.LEFT_BUTTON: Any = ...
    MIDDLE_BUTTON: Any = ...
    RIGHT_BUTTON: Any = ...
    LED: Any = ...
    SCL: Any = ...
    SDA: Any = ...
    SCK: Any = ...
    MOSI: Any = ...
    MISO: Any = ...
    SND_CS: Any = ...
    SND_DREQ: Any = ...
    SND_RESET: Any = ...
    SND_XDCS: Any = ...
    DISP_BUSY: Any = ...
    DISP_CS: Any = ...
    DISP_DC: Any = ...
    DISP_RESET: Any = ...
    NEOPIXEL: Any = ...
    VIBRATION_MOTOR: Any = ...
    BATTERY_SENSE: Any = ...
