from typing import Any
"""
board
"""
    board.AUDIO_INT: Any = ...
    AUDIO_SYNC: Any = ...
    AUDIO_BCLK: Any = ...
    AUDIO_RXD: Any = ...
    AUDIO_TXD: Any = ...
    AUDIO_MCLK: Any = ...
    ETHERNET_MDIO: Any = ...
    ETHERNET_MDC: Any = ...
    ETHERNET_RXD0: Any = ...
    ETHERNET_RXD1: Any = ...
    ETHERNET_CRS_DV: Any = ...
    ETHERNET_TXD0: Any = ...
    ETHERNET_TXD1: Any = ...
    ETHERNET_TXEN: Any = ...
    ETHERNET_INT: Any = ...
    ETHERNET_RST: Any = ...
    ETHERNET_CLK: Any = ...
    ETHERNET_RXER: Any = ...
    FREELINK_TX: Any = ...
    FREELINK_RX: Any = ...
    CAN_TX: Any = ...
    CAN_RX: Any = ...
    CAN_STBY: Any = ...
    ACCELEROMETER_SDA: Any = ...
    ACCELEROMETER_SCL: Any = ...
    I2C: Any = ...
    UART: Any = ...
